title: "Hellênikê / ἑλληνική: an open-source introduction to ancient Greek"
author: [Mary Ebbott, Neel Smith]
book: true
titlepage: true
titlepage-text-color: "FFFFFF"
titlepage-background: "cover.jpg"
